In [3]:
from __future__ import print_function
import torch

print('started')

started


In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 1.4013e-45, 4.2424e-08],
        [1.3445e+22, 1.3672e-05, 2.6102e+20],
        [8.3020e-10, 2.1887e+23, 2.1352e+20],
        [1.6969e-07, 5.2902e-08, 8.3391e-10],
        [2.5966e+20, 3.2919e-09, 1.0524e+21]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1762, 0.0404, 0.3729],
        [0.9150, 0.8429, 0.0846],
        [0.6647, 0.1019, 0.7414],
        [0.5698, 0.0449, 0.1287],
        [0.0987, 0.2725, 0.7853]])


In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5, 3, dtype=torch.long)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[ 1.7184, -1.6967,  0.6117],
        [ 0.1704, -0.5130, -1.4337],
        [-0.1372,  0.6687,  0.8245],
        [ 0.0041,  0.2856,  0.7284],
        [-0.6177, -0.9489,  0.4302]])


In [11]:
print(x.size())

torch.Size([5, 3])


In [12]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.8031, -1.1951,  1.5986],
        [ 0.7792, -0.5035, -1.4191],
        [-0.0988,  1.4943,  0.9598],
        [ 0.9298,  1.0966,  1.1970],
        [ 0.0258, -0.5347,  1.3520]])


In [13]:
print(torch.add(x, y))

tensor([[ 1.8031, -1.1951,  1.5986],
        [ 0.7792, -0.5035, -1.4191],
        [-0.0988,  1.4943,  0.9598],
        [ 0.9298,  1.0966,  1.1970],
        [ 0.0258, -0.5347,  1.3520]])


In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.8031, -1.1951,  1.5986],
        [ 0.7792, -0.5035, -1.4191],
        [-0.0988,  1.4943,  0.9598],
        [ 0.9298,  1.0966,  1.1970],
        [ 0.0258, -0.5347,  1.3520]])


In [15]:
y.add_(x)
print(y)

tensor([[ 1.8031, -1.1951,  1.5986],
        [ 0.7792, -0.5035, -1.4191],
        [-0.0988,  1.4943,  0.9598],
        [ 0.9298,  1.0966,  1.1970],
        [ 0.0258, -0.5347,  1.3520]])


In [16]:
print(x[:, 1])

tensor([-1.6967, -0.5130,  0.6687,  0.2856, -0.9489])


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7570])
0.7570164799690247


In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [24]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))